### PR TITLE
fix: vite polyfill

### PR DESCRIPTION
**Pull request by mrdotb**
The vite polyfill which is https://guybedford.com/es-module-preloading-integrity#modulepreload-polyfill under the hood should not be loaded in SSR context When doing react SSR it can create transient error I could not reproduce this with vue.
Loading the polyfill only in app.js which live_vue example already does seems the way to go.

I can't reproduce the issue on live_vue but I'm like 99% sure that it's incorrect to load the polyfill in SSR context.

Here is the error for reference it's transient.
```
✘ [ERROR] Missing "./modulepreload-polyfill" specifier in "vite" package [plugin vite:dep-pre-bundle]

    react/index.js:2:7:
      2 │ import "vite/modulepreload-polyfill";
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/john/Projects/elixir/jj/assets/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:46871:13)
    at handlePlugins (/home/john/Projects/elixir/jj/assets/node_modules/esbuild/lib/main.js:1150:21)
    at buildOrContextImpl (/home/john/Projects/elixir/jj/assets/node_modules/esbuild/lib/main.js:873:5)
    at Object.buildOrContext (/home/john/Projects/elixir/jj/assets/node_modules/esbuild/lib/main.js:699:5)
    at /home/john/Projects/elixir/jj/assets/node_modules/esbuild/lib/main.js:2032:68
    at new Promise (<anonymous>)
    at Object.context (/home/john/Projects/elixir/jj/assets/node_modules/esbuild/lib/main.js:2032:27)
    at Object.context (/home/john/Projects/elixir/jj/assets/node_modules/esbuild/lib/main.js:1874:58)
    at prepareEsbuildOptimizerRun (file:///home/john/Projects/elixir/jj/assets/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:50861:33)
```

### CODE REVIEW

**Comment by Valian** [comment]
@mrdotb Thank you! Just, I don't think it's necessary.

I've had some issues with it in the past (import not found), so I went extra mile to understand what's happening. It turns out, `vite/modulepreload-polyfill` is a special import resolved by a vite plugin. You can check it's source code [here](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/modulePreloadPolyfill.ts).

If it's SSR environment, then it does nothing. So it shouldn't be an issue.

Your error might come from [disabling modulepreload polyfill in vite config](https://vite.dev/config/build-options#build-modulepreload). 

Or maybe you somehow included it into dependencies, since your error is about "pre-dep-bundle", so external assets bundled by vite and stored on disk for quick reuse?

**Comment by mrdotb** [comment]
It's a transient error let's say I comment the import and run a build and un comment it does not appear again.
Removing the import from the react/index.js entrypoint prevent this error completely so I just guess it's SSR related.

I don't think the vite js config modulepreload is relevant since our entrypoint are ts or js and it seems to only affect html file entry point.

I did not include it in dependencies.

Is there any reason you have the import in the `app.js` and `vue/index.js` in the example ?

**Comment by Valian** [comment]
I think it must be a leftover! Thanks for pointing it out, will remove it. 

In your case it's about dependency pre-bundling (`plugin vite:dep-pre bundle`). I wonder if you could reproduce it by removing `node_modules/.vite/deps` and starting vite server again? 🤔

**Comment by mrdotb** [comment]
It reproduce the issue. Still I will leave the import polyfill in the app.js for the time being.
I am not sure how to fix the error otherwise.

I close this then thanks for the input.

**Comment by Valian** [comment]
Still your problem puzzles me... it shouldn't matter where that import is, you should get the same error anyway 🤔

**Pull request closed without merging**
